# Properties for the Kinetic Request CE 
## Server Address
server: "http://test.company.com/kinetic"
## System Admin User
adminUser: "admin"
## System Admin Password
adminPassword: ""
## Integration User
integrationUser: "test@kineticdata.com"
## Integration Password
integrationPassword: "xyz"
## log level (info | debug)
log_level: "info"